/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Chamada;
import classes.Cliente;
import classes.Motorista;
import classes.Veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class FazerChamada extends javax.swing.JFrame {
    static  ArrayList<Chamada> chamadaVector;
    /**
     * Creates new form FazerChamada
     */
    public FazerChamada() {
        initComponents();
        carregarClientes();
        carregarMotoristas();
        carregarVeiculos();
        chamadaVector = new ArrayList<Chamada>();
        
    }
    
    public void carregarClientes(){
        cmbSelecionarClienteChamada.removeAllItems();
        cmbSelecionarClienteChamada.addItem("Selecione o cliente");
        
        for (int i = 0; i < CadastroCliente.clienteVector.size(); i++){
            cmbSelecionarClienteChamada.addItem(CadastroCliente.clienteVector.get(i).getNome());
        }
    
    }
    public void carregarMotoristas(){
        cmbSelecionarMotoristaChamada.removeAllItems();
        cmbSelecionarMotoristaChamada.addItem("Selecione o motorista");
        
        for (int i = 0; i < CadastroMotorista.motoristaVector.size(); i++){
            cmbSelecionarMotoristaChamada.addItem(CadastroMotorista.motoristaVector.get(i).getNome());
        }
    
    }
    public void carregarVeiculos(){
        cmbSelecionarVeiculoChamada.removeAllItems();
        cmbSelecionarVeiculoChamada.addItem("Selecione o veículo");
        
        for (int i = 0; i < CadastroVeiculo.veiculoVector.size(); i++){
            cmbSelecionarVeiculoChamada.addItem(CadastroVeiculo.veiculoVector.get(i).getPlaca());
        }
    
    }
    public void carregarTabelaChamada(){
        DefaultTableModel modeloCH = new DefaultTableModel(new Object[] {"Id","Data","tipo","origem","destino","Horario de Partida","Horario de retorno",
            "Km inicial","Km final","Valor total","veiculo(placa)","Motorista(nome)","Cliente(nome)"},0);
        for(int i = 0; i < chamadaVector.size();i++){
            Object linha[] = new Object[]{chamadaVector.get(i).getId(),chamadaVector.get(i).getData(),chamadaVector.get(i).getTipo(),
            chamadaVector.get(i).getOrigem(),chamadaVector.get(i).getDestino(),chamadaVector.get(i).getHorarioPartida(),
            chamadaVector.get(i).getHorarioRetorno(),chamadaVector.get(i).getKmInicial(),chamadaVector.get(i).getKmFinal(),
            chamadaVector.get(i).getValorTotal(),chamadaVector.get(i).veiculo1.getPlaca(),
            chamadaVector.get(i).motorista1.getNome(), chamadaVector.get(i).cliente1.getNome()};
            
            modeloCH.addRow(linha);
        }
        tblChamada.setModel(modeloCH);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btngTipoChamada = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDestinoChamada = new javax.swing.JTextField();
        txtOrigemChamada = new javax.swing.JTextField();
        txtIdChamada = new javax.swing.JTextField();
        txtKmInicial = new javax.swing.JTextField();
        txtKmFinal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnTipoCorrida = new javax.swing.JRadioButton();
        btnTipoViagem = new javax.swing.JRadioButton();
        txtChamadaHorarioPartida = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtChamadaHorarioRetorno = new javax.swing.JFormattedTextField();
        txtDataChamada = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbSelecionarClienteChamada = new javax.swing.JComboBox<>();
        btnSalvarChamada = new javax.swing.JButton();
        btnCancelarChamada = new javax.swing.JButton();
        btnSairChamada = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtValortotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbSelecionarMotoristaChamada = new javax.swing.JComboBox<>();
        cmbSelecionarVeiculoChamada = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamada = new javax.swing.JTable();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Informações da chamada");

        jLabel2.setText("Id");

        jLabel3.setText("Data");

        jLabel5.setText("Tipo");

        jLabel6.setText("Origem");

        jLabel7.setText("Destino");

        jLabel8.setText("Horario de Partida");

        jLabel9.setText("Horario de Retorno");

        jLabel10.setText("Km inicial");

        jLabel11.setText("Km final");

        txtOrigemChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigemChamadaActionPerformed(evt);
            }
        });

        jLabel13.setText("HH:mm:ss");

        btngTipoChamada.add(btnTipoCorrida);
        btnTipoCorrida.setSelected(true);
        btnTipoCorrida.setText("Corrida");
        btnTipoCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCorridaActionPerformed(evt);
            }
        });

        btngTipoChamada.add(btnTipoViagem);
        btnTipoViagem.setText("viagem");

        txtChamadaHorarioPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));

        jLabel15.setText("HH:mm:ss");

        txtChamadaHorarioRetorno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));

        try {
            txtDataChamada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataChamadaActionPerformed(evt);
            }
        });

        jLabel4.setText("xx/xx/xxxx");

        jLabel12.setText("Cliente:");

        cmbSelecionarClienteChamada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbSelecionarClienteChamada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione um cliente" }));
        cmbSelecionarClienteChamada.setToolTipText("");
        cmbSelecionarClienteChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelecionarClienteChamadaActionPerformed(evt);
            }
        });

        btnSalvarChamada.setText("Salvar");
        btnSalvarChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarChamadaActionPerformed(evt);
            }
        });

        btnCancelarChamada.setText("Cancelar");
        btnCancelarChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarChamadaActionPerformed(evt);
            }
        });

        btnSairChamada.setText("Sair");
        btnSairChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairChamadaActionPerformed(evt);
            }
        });

        jLabel14.setText("Valor Total:");

        jLabel16.setText("Motorista:");

        jLabel17.setText("veiculo:");

        cmbSelecionarMotoristaChamada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbSelecionarMotoristaChamada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um motorista" }));

        cmbSelecionarVeiculoChamada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbSelecionarVeiculoChamada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um veiculo" }));

        tblChamada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Data", "Tipo", "Origem", "Destino", "Horario de Partida", "Horario de Retorno", "Km inicial", "Km final", "Valor total", "Veiculo(placa)", "Motorista(nome)", "Cliente(nome)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblChamada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChamada.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tblChamadaComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamada);
        if (tblChamada.getColumnModel().getColumnCount() > 0) {
            tblChamada.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblChamada.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblChamada.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblChamada.getColumnModel().getColumn(6).setPreferredWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtChamadaHorarioRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtChamadaHorarioPartida)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKmFinal)
                                    .addComponent(txtKmInicial))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(634, 634, 634))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarChamada)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarChamada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSairChamada)
                        .addGap(353, 353, 353))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDestinoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrigemChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdChamada, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataChamada, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnTipoCorrida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnTipoViagem)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(30, 30, 30)
                                    .addComponent(cmbSelecionarClienteChamada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbSelecionarMotoristaChamada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(30, 30, 30)
                                    .addComponent(cmbSelecionarVeiculoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnTipoCorrida)
                    .addComponent(btnTipoViagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtOrigemChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDestinoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(txtChamadaHorarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(txtChamadaHorarioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtKmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbSelecionarClienteChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbSelecionarMotoristaChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbSelecionarVeiculoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarChamada)
                    .addComponent(btnCancelarChamada)
                    .addComponent(btnSairChamada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrigemChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigemChamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigemChamadaActionPerformed

    private void cmbSelecionarClienteChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelecionarClienteChamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelecionarClienteChamadaActionPerformed

    private void btnSalvarChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarChamadaActionPerformed
        // TODO add your handling code here:
        int indexC = cmbSelecionarClienteChamada.getSelectedIndex();
        int indexM = cmbSelecionarMotoristaChamada.getSelectedIndex();
        int indexV = cmbSelecionarVeiculoChamada.getSelectedIndex();
        int id;
        String[] data = new String[3];
        String dataJoin;
        String tipo;
        String origem;
        String destino;
        String horarioPartida;
        String horarioRetorno;
        double kmInicial;
        double kmFinal;
        double valorTotal;
        Chamada chamadaDado;
        Cliente cliente;
        Veiculo veiculo;
        Motorista motorista;
        
        id = Integer.parseInt(txtIdChamada.getText());
        data = txtDataChamada.getText().split("/");
        dataJoin = String.join("/", data);
        tipo = "corrida";
        if (btnTipoCorrida.isSelected()){
            tipo = "corrida";
        }
        if (btnTipoViagem.isSelected()){
            tipo = "viagem";
        }
        origem = txtOrigemChamada.getText();
        destino = txtDestinoChamada.getText();
        horarioPartida = (txtChamadaHorarioPartida.getText());
        horarioRetorno = (txtChamadaHorarioRetorno.getText());
        kmInicial = Double.parseDouble(txtKmInicial.getText());
        kmFinal = Double.parseDouble(txtKmFinal.getText());
        valorTotal = Double.parseDouble(txtValortotal.getText());
        cliente = CadastroCliente.clienteVector.get(indexC-1);
        motorista = CadastroMotorista.motoristaVector.get(indexM-1);
        veiculo = CadastroVeiculo.veiculoVector.get(indexV-1);
        chamadaDado = new Chamada(id, dataJoin, tipo, origem, destino, horarioPartida, 
                horarioRetorno, kmInicial, kmFinal, valorTotal, cliente, veiculo, motorista);
        
        chamadaVector.add(chamadaDado);
        JOptionPane.showMessageDialog(null, "Chamada feita com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        carregarTabelaChamada();
        txtChamadaHorarioPartida.setText("");
        txtChamadaHorarioRetorno.setText("");
        txtDataChamada.setText("");
        txtDestinoChamada.setText("");
        txtIdChamada.setText("");
        txtKmFinal.setText("");
        txtKmInicial.setText("");
        txtOrigemChamada.setText("");
        txtValortotal.setText("");
        cmbSelecionarClienteChamada.removeAllItems();
        cmbSelecionarClienteChamada.addItem("Selecione um cliente");
        cmbSelecionarMotoristaChamada.removeAllItems();
        cmbSelecionarMotoristaChamada.addItem("Selecione um motorista");
        cmbSelecionarVeiculoChamada.removeAllItems();
        cmbSelecionarVeiculoChamada.addItem("Selecione um veiculo");
        
        
    }//GEN-LAST:event_btnSalvarChamadaActionPerformed

    private void btnTipoCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTipoCorridaActionPerformed

    private void tblChamadaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblChamadaComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_tblChamadaComponentResized

    private void btnSairChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairChamadaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSairChamadaActionPerformed

    private void btnCancelarChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarChamadaActionPerformed
        // TODO add your handling code here:
        txtChamadaHorarioPartida.setText("");
        txtChamadaHorarioRetorno.setText("");
        txtDataChamada.setText("");
        txtDestinoChamada.setText("");
        txtIdChamada.setText("");
        txtKmFinal.setText("");
        txtKmInicial.setText("");
        txtOrigemChamada.setText("");
        txtValortotal.setText("");
    }//GEN-LAST:event_btnCancelarChamadaActionPerformed

    private void txtDataChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataChamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataChamadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerChamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerChamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerChamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerChamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerChamada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarChamada;
    private javax.swing.JButton btnSairChamada;
    private javax.swing.JButton btnSalvarChamada;
    private javax.swing.JRadioButton btnTipoCorrida;
    private javax.swing.JRadioButton btnTipoViagem;
    private javax.swing.ButtonGroup btngTipoChamada;
    private javax.swing.JComboBox<String> cmbSelecionarClienteChamada;
    private javax.swing.JComboBox<String> cmbSelecionarMotoristaChamada;
    private javax.swing.JComboBox<String> cmbSelecionarVeiculoChamada;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChamada;
    private javax.swing.JFormattedTextField txtChamadaHorarioPartida;
    private javax.swing.JFormattedTextField txtChamadaHorarioRetorno;
    private javax.swing.JFormattedTextField txtDataChamada;
    private javax.swing.JTextField txtDestinoChamada;
    private javax.swing.JTextField txtIdChamada;
    private javax.swing.JTextField txtKmFinal;
    private javax.swing.JTextField txtKmInicial;
    private javax.swing.JTextField txtOrigemChamada;
    private javax.swing.JTextField txtValortotal;
    // End of variables declaration//GEN-END:variables
}
