/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.util.*;
import javax.swing.JOptionPane;
import static telas.CadastroCliente.clienteVector;
import static telas.CadastroMotorista.motoristaVector;
import static telas.CadastroVeiculo.veiculoVector;

/**
 *
 * @author Eduardo Ferreira Marques Cavalcante
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChamarCadastro = new javax.swing.JButton();
        btnFazerChamada = new javax.swing.JButton();
        btnSairSystem = new javax.swing.JButton();
        btnComentario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnChamarCadastro.setText("Cadastrar");
        btnChamarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarCadastroActionPerformed(evt);
            }
        });

        btnFazerChamada.setText("Chamada");
        btnFazerChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerChamadaActionPerformed(evt);
            }
        });

        btnSairSystem.setText("Sair e fechar");
        btnSairSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairSystemActionPerformed(evt);
            }
        });

        btnComentario.setText("Comentario");
        btnComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Clique aqui antes de começar a cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnChamarCadastro)
                        .addGap(72, 72, 72)
                        .addComponent(btnFazerChamada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnComentario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSairSystem)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComentario)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamarCadastro)
                    .addComponent(btnFazerChamada))
                .addGap(68, 68, 68)
                .addComponent(btnSairSystem)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChamarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarCadastroActionPerformed
        // TODO add your handling code here:
        new SelecionarCadastro().setVisible(true);
        
    }//GEN-LAST:event_btnChamarCadastroActionPerformed

    private void btnFazerChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerChamadaActionPerformed
        // TODO add your handling code here:
        
        if (clienteVector == null || motoristaVector == null || veiculoVector == null){
            JOptionPane.showMessageDialog(null, "Ainda não há nenhum clientes, ou veiculos ou motoristas cadastrados!", "Mensagem", JOptionPane.ERROR_MESSAGE);
        }else{
            new FazerChamada().setVisible(true);
        }
        

    }//GEN-LAST:event_btnFazerChamadaActionPerformed

    private void btnSairSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairSystemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairSystemActionPerformed

    private void btnComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Para começar a cadastrar é preciso que 1 instancia de cada tela(Cliente, Motorista e Veiculo),"
                + "estejam abertas, não feche ou saia da de nenhuma dessas telas, igual no programa exemplo da aula 6.", "Mensagem", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnComentarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamarCadastro;
    private javax.swing.JButton btnComentario;
    private javax.swing.JButton btnFazerChamada;
    private javax.swing.JButton btnSairSystem;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
